org: ddavies90
app: ps5-alert
service: ps5-alert-nodejs

frameworkVersion: '2'


provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(15 minutes)
  cronHandler:
    handler: handler.run
    events:
      - schedule: cron(0/15 7-23 * * ? *)
